### ISSUE TITLE
Ideas: Once Planned but Missing Features in Nova

### ISSUE THREAD

**Issue by p0n1** [blockhackersio/zrclib#1]
The following are plans that the Tornado Cash team once had but have not yet implemented. Perhaps we can draw inspiration from them. 

> With its customized amounts & shielded transfers, Tornado Cash Nova is the first step towards this new & improved version of Tornado Cash. Future plans for the protocol include the possibility of making atomic swaps within a shielded pool, as well as a pool that will be able to support ERC20 tokens & NFT.

Source: https://tornado-cash.medium.com/tornado-cash-introduces-arbitrary-amounts-shielded-transfers-8df92d93c37c

**Comment by ryardley** [comment]
Yep I believe this could be done with a multiasset shielded pool: https://youtu.be/r25azD2MFnI

**Comment by ryardley** [comment]
Would be nice to have an escrow feature.
