### ISSUE TITLE
Contract input arguments should be formatted in SDK

### ISSUE THREAD

**Issue by eerkaijun** [blockhackersio/zrclib#16]
In the `MyPool.ts` (test file)[https://github.com/blockhackersio/zrclib/blob/main/integration/test/MyPool.ts], I've added a function `formatArguments` which format the output `{ args, extData }` from the ZRC sdk to be compatible to the contract function. I think it will be better for this function to be included in the sdk so developers do not have to worry about it at all.

**Comment by ryardley** [comment]
Done https://github.com/blockhackersio/zrclib/commit/4ce5f8ff5ed8833f869487645489d8d22abbd948
