### ISSUE TITLE
Potential Double Spend Issue Because `inputNullifiers` and `outputCommitments` Are Not Bound With Public Input

### ISSUE THREAD

**Issue by p0n1** [blockhackersio/zrclib#17]
There seems to be a potential double spend issue because `inputNullifiers` and `outputCommitments` are not bound with the public input.

It appears we have a `pubSignals` array for all public inputs:

https://github.com/blockhackersio/zrclib/blob/4ce5f8ff5ed8833f869487645489d8d22abbd948/tools/src/get_proof.ts#L160-L177

However, we still have separate `inputNullifiers` and `outputCommitments` fields in the `ProofArguments` struct, which are used later in the smart contracts. Since they're not bound to the circuit, they could be assigned any value, potentially leading to security issues.

```solidity
    struct ProofArguments {
        bytes proof;
        uint[] pubSignals;
        bytes32 root;
        bytes32[] inputNullifiers;
        bytes32[2] outputCommitments;
        uint256 publicAmount;
        bytes32 extDataHash;
    }
```

https://github.com/blockhackersio/zrclib/blob/4ce5f8ff5ed8833f869487645489d8d22abbd948/tools/contracts/ZRC20.sol#L96-L109

To address this issue, we must ensure that the public input value (and everything used for smart contracts) is bound to the circuit, just like the original Tornado Nova code does.

https://github.com/tornadocash/tornado-nova/blob/f9264eeffe48bf5e04e19d8086ee6ec58cdf0d9e/contracts/TornadoPool.sol#L210-L220

**Comment by eerkaijun** [comment]
Fixed in this commit: https://github.com/blockhackersio/zrclib/commit/254a87287b9bc28459128559fa5fd1d90667f566
