### ISSUE TITLE
b2sum package is required

### ISSUE THREAD

**Issue by p0n1** [blockhackersio/zrclib#2]
I ran into error bellow with `pnpm install`.

```
│ ./scripts/install.sh: line 9: b2sum: command not found
│ Danger!!! Powers of Tau file is incorrect.
└─ Failed in 5m 23.1s at /Users/p/zrclib/tools
 ELIFECYCLE  Command failed with exit code 1.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
```

Then I install b2sum package by `brew install b2sum` and run again. It works for me on MacOS.

https://github.com/blockhackersio/zrclib/blob/faed99fc97230b268676e117e666b4ba109020dc/tools/scripts/install.sh#L9

Maybe we can add `b2sum` into prerequisite section in README if we do not want handle its installation in scripts now.

**Comment by ryardley** [comment]
Added to readme :)!
