### ISSUE TITLE
Questions on transact function of ZUSD

### ISSUE THREAD

**Issue by p0n1** [blockhackersio/zrclib#25]
I have some questions about the `transact()` function of ZUSD contract when reading the code.

In the following code snippet, why do we need to spend an allowance when depositing, considering we're using the internal `_transfer` function of the ERC20 token?

https://github.com/blockhackersio/zrclib/blob/06a211bf576b4fb3d707228908057f9733f136f5/examples/stablecoin/contracts/ZUSD.sol#L39-L43

In the next code snippet, why is the balance subtracted from `msg.sender` instead of `address(this)` when withdrawing from the pool?

https://github.com/blockhackersio/zrclib/blob/06a211bf576b4fb3d707228908057f9733f136f5/examples/stablecoin/contracts/ZUSD.sol#L61-L65

**Comment by eerkaijun** [comment]
Good catch, fixed now!
