### ISSUE TITLE
Implement indexDB encrypted store 

### ISSUE THREAD

**Issue by ryardley** [blockhackersio/zrclib#28]
So far we are using an encrypted in memory store. 
Using an indexDB encrypted store will mean users will be able to login with their passwords without resorting to using their metamask accounts

**Comment by eerkaijun** [comment]
@ryardley in the tests, there seems to be some error caught in the indexdb module (though because of error handling, the tests still pass). 

```
@zrclib/tests:test:     at ObjectStore.storeRecord (/home/runner/work/zrclib/zrclib/node_modules/.pnpm/fake-indexeddb@4.0.1/node_modules/fake-indexeddb/build/cjs/lib/ObjectStore.js:148:15)
@zrclib/tests:test:     at FDBTransaction._start (/home/runner/work/zrclib/zrclib/node_modules/.pnpm/fake-indexeddb@4.0.1/node_modules/fake-indexeddb/build/cjs/FDBTransaction.js:179:26)
@zrclib/tests:test:     at Immediate.<anonymous> (/home/runner/work/zrclib/zrclib/node_modules/.pnpm/fake-indexeddb@4.0.1/node_modules/fake-indexeddb/build/cjs/lib/Database.js:38:16)
@zrclib/tests:test:     at processImmediate (node:internal/timers:476:21)
@zrclib/tests:test: onNullifier 0x2ba0406a40b70edb978bb4e454553004bfbe5b723aa1e3882d44404dc18e23d5
@zrclib/tests:test: ConstraintError: A mutation operation in the transaction failed because a constraint was not satisfied. For example, an object such as an object store or index already exists and a request attempted to create a new one.
@zrclib/tests:test:     at ObjectStore.storeRecord (/home/runner/work/zrclib/zrclib/node_modules/.pnpm/fake-indexeddb@4.0.1/node_modules/fake-indexeddb/build/cjs/lib/ObjectStore.js:148:15)
@zrclib/tests:test:     at FDBTransaction._start (/home/runner/work/zrclib/zrclib/node_modules/.pnpm/fake-indexeddb@4.0.1/node_modules/fake-indexeddb/build/cjs/FDBTransaction.js:179:26)
@zrclib/tests:test:     at Immediate.<anonymous> (/home/runner/work/zrclib/zrclib/node_modules/.pnpm/fake-indexeddb@4.0.1/node_modules/fake-indexeddb/build/cjs/lib/Database.js:38:16)
@zrclib/tests:test:     at processImmediate (node:internal/timers:476:21)
```

**Comment by ryardley** [comment]
Merged

**Comment by ryardley** [comment]
> @ryardley in the tests, there seems to be some error caught in the indexdb module (though because of error handling, the tests still pass).
> 
> ```
> @zrclib/tests:test:     at ObjectStore.storeRecord (/home/runner/work/zrclib/zrclib/node_modules/.pnpm/fake-indexeddb@4.0.1/node_modules/fake-indexeddb/build/cjs/lib/ObjectStore.js:148:15)
> @zrclib/tests:test:     at FDBTransaction._start (/home/runner/work/zrclib/zrclib/node_modules/.pnpm/fake-indexeddb@4.0.1/node_modules/fake-indexeddb/build/cjs/FDBTransaction.js:179:26)
> @zrclib/tests:test:     at Immediate.<anonymous> (/home/runner/work/zrclib/zrclib/node_modules/.pnpm/fake-indexeddb@4.0.1/node_modules/fake-indexeddb/build/cjs/lib/Database.js:38:16)
> @zrclib/tests:test:     at processImmediate (node:internal/timers:476:21)
> @zrclib/tests:test: onNullifier 0x2ba0406a40b70edb978bb4e454553004bfbe5b723aa1e3882d44404dc18e23d5
> @zrclib/tests:test: ConstraintError: A mutation operation in the transaction failed because a constraint was not satisfied. For example, an object such as an object store or index already exists and a request attempted to create a new one.
> @zrclib/tests:test:     at ObjectStore.storeRecord (/home/runner/work/zrclib/zrclib/node_modules/.pnpm/fake-indexeddb@4.0.1/node_modules/fake-indexeddb/build/cjs/lib/ObjectStore.js:148:15)
> @zrclib/tests:test:     at FDBTransaction._start (/home/runner/work/zrclib/zrclib/node_modules/.pnpm/fake-indexeddb@4.0.1/node_modules/fake-indexeddb/build/cjs/FDBTransaction.js:179:26)
> @zrclib/tests:test:     at Immediate.<anonymous> (/home/runner/work/zrclib/zrclib/node_modules/.pnpm/fake-indexeddb@4.0.1/node_modules/fake-indexeddb/build/cjs/lib/Database.js:38:16)
> @zrclib/tests:test:     at processImmediate (node:internal/timers:476:21)
> ```

Maybe we should look at that in a separate issue? There might be situations where errors print but are used to return true or false.
