### ISSUE TITLE
Ideas: Multiasset Shielded Pool

### ISSUE THREAD

**Issue by ryardley** [blockhackersio/zrclib#3]
It might be nice to create a multiasset shielded pool primitive which could mean people could increase their anonymity set and support multiple shielded tokens.  

https://github.com/anoma/masp/blob/main/docs/multi-asset-shielded-pool.pdf

There is a video about this protocol here https://youtu.be/r25azD2MFnI

**Comment by p0n1** [comment]
Cool. Looking into this and evaluating about the engineering efforts of it.

**Comment by ryardley** [comment]
Not quite sure 100% how atomic swaps would work though:
- You can pay multiple assets to multiple parties in a single transaction
- Could we use BLS somehow to create a joint keypair that can spend the escrow? Not sure of the ramifications within the context of a circuit

**Comment by p0n1** [comment]
I believe supporting different asset types in the circuit shouldn't be difficult if we're not dealing with multiple assets in one shielded transaction. After watching the video (https://youtu.be/r25azD2MFnI), I understand that a major refactor of the Tornado Nova circuit would be needed to support multi-asset shielded transfers in a single transaction.

As a first step, I plan to experiment with a simpler solution to become more familiar with the Circom code and other related aspects.

**Comment by p0n1** [comment]
ref: https://github.com/blockhackersio/zrclib/issues/14#issuecomment-1510051454

**Comment by eerkaijun** [comment]
Have been implemented and merged to `main`.
